# --- First Solution

SELECT LAT_N INTO @a FROM STATION ORDER BY LAT_N asc LIMIT 1;
SELECT LONG_W INTO @b FROM STATION ORDER BY LONG_W asc LIMIT 1;

SELECT LAT_N INTO @c FROM STATION ORDER BY LAT_N desc LIMIT 1;
SELECT LONG_W INTO @d FROM STATION ORDER BY LONG_W desc LIMIT 1;

SELECT ROUND((@c - @a) + (@d - @b), 4);

# ---- Second Solution

SELECT ROUND( (MAX(LAT_N) - MIN(LAT_N)) + (MAX(LONG_W) - MIN(LONG_W) )  , 4) FROM STATION;